#ifndef GAME_H
#define GAME_H

#include <stdint.h>
#include <stdbool.h>

// up, down, left and right are self-explanatory, actions contains four
//  different inputs that are game specific, e.g. jump or fire.
typedef struct input_s {
	float up, down, left, right;
	float actions[4];
} input_t;

// A structure generated by the game implementation, the player can't change
//  any of the values, they're only for information purposes.

struct game_s;
typedef struct game_s {
	const uint32_t screen_width, screen_height;
	const float* screen;
	const int32_t score;
	const bool game_over;

	// Sends a new input to the game and requests a new state to be written
	//  into <game>.
	void(*_update)(struct game_s* game, input_t input);
} game_t;

#endif // GAME_H
